package neu.edu.entity;
// Generated 2022��12��16�� ����2:32:19 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Companystatus generated by hbm2java
 */
@Entity
@Table(name = "companystatus", catalog = "rawmaterialsupplier")
public class Companystatus implements java.io.Serializable {

	private Integer idCompanyStatus;
	private String isActive;
	private String supplyChainIssue;
	private String companyName;
	private int wight;

	public Companystatus() {
	}

	public Companystatus(String isActive, String supplyChainIssue, String companyName, int wight) {
		this.isActive = isActive;
		this.supplyChainIssue = supplyChainIssue;
		this.companyName = companyName;
		this.wight = wight;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_company_status", unique = true, nullable = false)
	public Integer getIdCompanyStatus() {
		return this.idCompanyStatus;
	}

	public void setIdCompanyStatus(Integer idCompanyStatus) {
		this.idCompanyStatus = idCompanyStatus;
	}

	@Column(name = "is_active", nullable = false, length = 2)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "supply_chain_issue", nullable = false, length = 45)
	public String getSupplyChainIssue() {
		return this.supplyChainIssue;
	}

	public void setSupplyChainIssue(String supplyChainIssue) {
		this.supplyChainIssue = supplyChainIssue;
	}

	@Column(name = "company_name", nullable = false, length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "wight", nullable = false)
	public int getWight() {
		return this.wight;
	}

	public void setWight(int wight) {
		this.wight = wight;
	}

}
