package neu.edu.entity;
// Generated 2022��12��16�� ����3:55:32 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Materialinventory generated by hbm2java
 */
@Entity
@Table(name = "materialinventory", catalog = "rawmaterialsupplier")
public class Materialinventory implements java.io.Serializable {

	private Integer idRawMaterialAvailable;
	private int inventory;
	private int unitCost;
	private String companyName;
	private String material;

	public Materialinventory() {
	}

	public Materialinventory(int inventory, int unitCost, String companyName, String material) {
		this.inventory = inventory;
		this.unitCost = unitCost;
		this.companyName = companyName;
		this.material = material;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_raw_material_available", unique = true, nullable = false)
	public Integer getIdRawMaterialAvailable() {
		return this.idRawMaterialAvailable;
	}

	public void setIdRawMaterialAvailable(Integer idRawMaterialAvailable) {
		this.idRawMaterialAvailable = idRawMaterialAvailable;
	}

	@Column(name = "inventory", nullable = false)
	public int getInventory() {
		return this.inventory;
	}

	public void setInventory(int inventory) {
		this.inventory = inventory;
	}

	@Column(name = "unit_cost", nullable = false)
	public int getUnitCost() {
		return this.unitCost;
	}

	public void setUnitCost(int unitCost) {
		this.unitCost = unitCost;
	}

	@Column(name = "company_name", nullable = false, length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "material", nullable = false, length = 45)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

}
