package neu.edu.entity;
// Generated 2022��12��16�� ����3:10:41 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cityconnection generated by hbm2java
 */
@Entity
@Table(name = "cityconnection", catalog = "distributor")
public class Cityconnection implements java.io.Serializable {

	private Integer idCityConnection;
	private String companyName;
	private String city;
	private int shipTime;
	private int cost;

	public Cityconnection() {
	}

	public Cityconnection(String companyName, String city, int shipTime, int cost) {
		this.companyName = companyName;
		this.city = city;
		this.shipTime = shipTime;
		this.cost = cost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_city_connection", unique = true, nullable = false)
	public Integer getIdCityConnection() {
		return this.idCityConnection;
	}

	public void setIdCityConnection(Integer idCityConnection) {
		this.idCityConnection = idCityConnection;
	}

	@Column(name = "company_name", nullable = false, length = 50)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "city", nullable = false, length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ship_time", nullable = false)
	public int getShipTime() {
		return this.shipTime;
	}

	public void setShipTime(int shipTime) {
		this.shipTime = shipTime;
	}

	@Column(name = "cost", nullable = false)
	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

}
