package neu.edu.entity;
// Generated 2022��12��16�� ����3:10:41 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Productinventory generated by hbm2java
 */
@Entity
@Table(name = "productinventory", catalog = "distributor")
public class Productinventory implements java.io.Serializable {

	private Integer idProduct;
	private String companyName;
	private int inventory;
	private String productname;
	private Integer cost;

	public Productinventory() {
	}

	public Productinventory(String companyName, int inventory, String productname) {
		this.companyName = companyName;
		this.inventory = inventory;
		this.productname = productname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_product", unique = true, nullable = false)
	public Integer getIdProduct() {
		return this.idProduct;
	}

	public void setIdProduct(Integer idProduct) {
		this.idProduct = idProduct;
	}

	@Column(name = "company_name", nullable = false, length = 50)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "inventory", nullable = false)
	public int getInventory() {
		return this.inventory;
	}

	public void setInventory(int inventory) {
		this.inventory = inventory;
	}

	@Column(name = "productname", nullable = false, length = 20)
	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "cost", nullable = false)
	public Integer getCost() {
		return cost;
	}

	public void setCost(Integer cost) {
		this.cost = cost;
	}

	
}
