package neu.edu.entity;
// Generated 2022��12��16�� ����2:36:51 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Companyproduct generated by hbm2java
 */
@Entity
@Table(name = "companyproduct", catalog = "manufacture")
public class Companyproduct implements java.io.Serializable {

	private Integer idCompanyProduct;
	private String companyName;
	private String productName;
	private int inventory;

	public Companyproduct() {
	}

	public Companyproduct(String companyName, String productName, int inventory) {
		this.companyName = companyName;
		this.productName = productName;
		this.inventory = inventory;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_company_product", unique = true, nullable = false)
	public Integer getIdCompanyProduct() {
		return this.idCompanyProduct;
	}

	public void setIdCompanyProduct(Integer idCompanyProduct) {
		this.idCompanyProduct = idCompanyProduct;
	}

	@Column(name = "company_name", nullable = false, length = 50)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "product_name", nullable = false, length = 20)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "inventory", nullable = false)
	public int getInventory() {
		return this.inventory;
	}

	public void setInventory(int inventory) {
		this.inventory = inventory;
	}

}
