package neu.edu.entity;
// Generated 2022��12��16�� ����2:36:51 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Distributororder generated by hbm2java
 */
@Entity
@Table(name = "distributororder", catalog = "manufacture")
public class Distributororder implements java.io.Serializable {

	private Integer idDistributorOrder;
	private String productName;
	private String companyName;
	private String distributorCompany;
	private int amount;
	private String status;

	public Distributororder() {
	}

	public Distributororder(String productName, String companyName, String distributorCompany, int amount,
			String status) {
		this.productName = productName;
		this.companyName = companyName;
		this.distributorCompany = distributorCompany;
		this.amount = amount;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_distributor_order", unique = true, nullable = false)
	public Integer getIdDistributorOrder() {
		return this.idDistributorOrder;
	}

	public void setIdDistributorOrder(Integer idDistributorOrder) {
		this.idDistributorOrder = idDistributorOrder;
	}

	@Column(name = "product_name", nullable = false, length = 45)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "company_name", nullable = false, length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "distributor_company", nullable = false, length = 50)
	public String getDistributorCompany() {
		return this.distributorCompany;
	}

	public void setDistributorCompany(String distributorCompany) {
		this.distributorCompany = distributorCompany;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Column(name = "status", nullable = false, length = 19)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
