package neu.edu.entity;
// Generated 2022��12��16�� ����2:36:51 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Materialorder generated by hbm2java
 */
@Entity
@Table(name = "materialorder", catalog = "manufacture")
public class Materialorder implements java.io.Serializable {

	private Integer idMaterialOrder;
	private String supplierCompany;
	private String materialName;
	private int unitCost;
	private int amount;
	private String statu;
	private String companyName;

	public Materialorder() {
	}

	public Materialorder(String supplierCompany, String materialName, int unitCost, int amount, String statu,
			String companyName) {
		this.supplierCompany = supplierCompany;
		this.materialName = materialName;
		this.unitCost = unitCost;
		this.amount = amount;
		this.statu = statu;
		this.companyName = companyName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_material_order", unique = true, nullable = false)
	public Integer getIdMaterialOrder() {
		return this.idMaterialOrder;
	}

	public void setIdMaterialOrder(Integer idMaterialOrder) {
		this.idMaterialOrder = idMaterialOrder;
	}

	@Column(name = "supplier_company", nullable = false, length = 20)
	public String getSupplierCompany() {
		return this.supplierCompany;
	}

	public void setSupplierCompany(String supplierCompany) {
		this.supplierCompany = supplierCompany;
	}

	@Column(name = "material_name", nullable = false, length = 20)
	public String getMaterialName() {
		return this.materialName;
	}

	public void setMaterialName(String materialName) {
		this.materialName = materialName;
	}

	@Column(name = "unit_cost", nullable = false)
	public int getUnitCost() {
		return this.unitCost;
	}

	public void setUnitCost(int unitCost) {
		this.unitCost = unitCost;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Column(name = "statu", nullable = false, length = 8)
	public String getStatu() {
		return this.statu;
	}

	public void setStatu(String statu) {
		this.statu = statu;
	}

	@Column(name = "company_name", nullable = false, length = 50)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

}
