package neu.edu.entity;
// Generated 2022��12��16�� ����2:36:51 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Materialinventory generated by hbm2java
 */
@Entity
@Table(name = "materialinventory", catalog = "manufacture")
public class Materialinventory implements java.io.Serializable {

	private Integer idMaterialInventory;
	private String companyName;
	private int amount;
	private String materialName;

	public Materialinventory() {
	}

	public Materialinventory(String companyName, int amount, String materialName) {
		this.companyName = companyName;
		this.amount = amount;
		this.materialName = materialName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_material_inventory", unique = true, nullable = false)
	public Integer getIdMaterialInventory() {
		return this.idMaterialInventory;
	}

	public void setIdMaterialInventory(Integer idMaterialInventory) {
		this.idMaterialInventory = idMaterialInventory;
	}

	@Column(name = "company_name", nullable = false, length = 30)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Column(name = "material_name", nullable = false, length = 45)
	public String getMaterialName() {
		return this.materialName;
	}

	public void setMaterialName(String materialName) {
		this.materialName = materialName;
	}

}
