package neu.edu.entity;
// Generated 2022��12��16�� ����2:36:51 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Supplierconnection generated by hbm2java
 */
@Entity
@Table(name = "supplierconnection", catalog = "manufacture")
public class Supplierconnection implements java.io.Serializable {

	private Integer idSupplierConnection;
	private String companyName;
	private String supplierCompanyName;
	private String transportation;
	private int time;
	private int cost;

	public Supplierconnection() {
	}

	public Supplierconnection(String companyName, String supplierCompanyName, String transportation, int time,
			int cost) {
		this.companyName = companyName;
		this.supplierCompanyName = supplierCompanyName;
		this.transportation = transportation;
		this.time = time;
		this.cost = cost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_supplier_connection", unique = true, nullable = false)
	public Integer getIdSupplierConnection() {
		return this.idSupplierConnection;
	}

	public void setIdSupplierConnection(Integer idSupplierConnection) {
		this.idSupplierConnection = idSupplierConnection;
	}

	@Column(name = "company_name", nullable = false, length = 50)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "supplier_company_name", nullable = false, length = 50)
	public String getSupplierCompanyName() {
		return this.supplierCompanyName;
	}

	public void setSupplierCompanyName(String supplierCompanyName) {
		this.supplierCompanyName = supplierCompanyName;
	}

	@Column(name = "transportation", nullable = false, length = 7)
	public String getTransportation() {
		return this.transportation;
	}

	public void setTransportation(String transportation) {
		this.transportation = transportation;
	}

	@Column(name = "time", nullable = false)
	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	@Column(name = "cost", nullable = false)
	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

}
